### ISSUE TITLE
Overwriting maximum file size for upload.

### ISSUE THREAD

**Issue by vibhor-webonise** [zyro23/grails-core-668#2]
Hey,
Looked at the repo, and tried to find a solution to have a size defined for file upload using ,
upload:
            maxFileSize: 9999999999
            maxRequestSize: 9999999999

But as in Grails 3 default size is 128000 (~128KB). It is not allowing us to get over it even after defining a bigger value in the yml file.

Please suggest.
Vibhor Kansal
git id : vibhor-webonise.

**Comment by zyro23** [comment]
try (grails-3.1.9):

```
grails:
    controllers:
            upload:
                maxFileSize: 9999999999
                maxRequestSize: 9999999999
```

ref:
- https://github.com/grails/grails-core/blob/v3.1.9/grails-core/src/main/groovy/grails/config/Settings.groovy#L110
- https://github.com/grails/grails-core/blob/v3.1.9/grails-core/src/main/groovy/grails/config/Settings.groovy#L115
